### ISSUE TITLE
Additional input fields

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#10]
## Value Proposition

As a beaver I want to type in more details to a memory 
to be able to better recall that moment
I need extra input fields

## Description

![Screenshot](https://user-images.githubusercontent.com/116001730/210781876-deb7d71a-1782-444b-940e-701d2d7d9ddc.png)

---
## Acceptance Criteria

- input for Memory:  Date, Header, Text, 

## Tasks

- [x] refactor form components
- [x] add input fields
- [x] extend `db/model`
- [x] display input on detail [id].js page
- [x] apply styling
- [x] write component test
