### ISSUE TITLE
create search

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#11]
## Value Proposition

As a beaver I need a search page
to be able to quickly find memories
in order to find details of a specific memory

## Description

![Image](https://user-images.githubusercontent.com/116001730/211155865-a38fc0b9-9bbb-467c-b606-d38ca0615cfa.png)

---
## Acceptance Criteria

- Text input below Header
- on change search for all memories

## Tasks

- [x] work on branch
- [x] write onChange function
- [x] add one input field
- [x] add basic styling
- [x] refactor where possible
