### ISSUE TITLE
create new memory card

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#12]
## Value Proposition

As a beaver 
I want to be able to create a memory card
in order to save memories

## Description

![Screenshot 2022-12-19 at 14 41 47](https://user-images.githubusercontent.com/116001730/208438984-03c5595e-4d59-4112-8ec0-fb33643c8557.png)

---
## Acceptance Criteria

- Button in Footer 
- Form where I can enter a memory
- Created memory is transferred to timeline

## Tasks

- [x] Add button to StyledFooterList 
- [x] add simple input fields
- [x] render created task
- [x] apply styling

**Comment by AntjeWalter** [comment]
Maybe you could create a scribble of how your input fields should look like so that it's easier for you to turn it into code. At least that's what's helping me to start coding. :)
