### ISSUE TITLE
implement database

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#18]
## Value Proposition

**As a** beaver

**I need** a database integration

**to be able to** save my memories globally.

## Description

A database integration with MongoDB Atlas

## Acceptance Criteria

- being able to read and create new memories

## Tasks

- [x] improve data structure
- [x] create collection with MongoDB
- [x] create api directory
- [x] write logic for the api
