### ISSUE TITLE
Edit a memory

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#19]
## Value Proposition

**As a** beaver

**I need** an edit button

**to be able to** edit and complete or correct a memory

## Description

![Image](https://user-images.githubusercontent.com/116001730/210520672-1b491bf5-e4c3-434f-abbe-11408e4f39cb.png)

## Acceptance Criteria

- by clicking the edit button an input field opens with previously entered 
- Edit button is displayed on Details page
 

## Tasks

- [x] create a basic edit button
- [x] implement the edit function
- [x] create edit state on List and Detailpage
- [x] add PUT method to `api/memories`
- [x] apply basic styling
