### ISSUE TITLE
Delete a memory

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#20]
## Value Proposition

**As a** beaver

**I need** an delete button

**to be able to** delete a memory

## Description

![Image](https://user-images.githubusercontent.com/116001730/210352494-56444e3f-cf0b-46fb-b254-5066da5aa6c1.png)

## Acceptance Criteria

- by clicking the delete button the memory is deleted from the array 
- Button is displayed
 

## Tasks

- [ ] redesign EventCard & EventCardDetails
- [ ] show delete button
- [ ] write logic to delete item/card from database
- [ ] apply simple styling
