### ISSUE TITLE
Redesign Overview page

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#32]
## Value Proposition

**As a** beaver

**I need** a better overview of all my memories

**to be able to** quickly find and remember certain moments

## Description

![Image](https://user-images.githubusercontent.com/116001730/212318056-602d0460-7fb1-4352-8513-26ce981d4885.png)

## Acceptance Criteria

- Greeting by name & time of the day
- Sorted List of memories
- dynamically Sorted List of recently created memories

## Tasks

- [x] create function that creates time sensitive greeting
- [x] create section for scrollable events
- [x] preparing date input for more details about the time
- [ ] insert new "Home" icon

**Comment by AntjeWalter** [comment]
Hi Andy, I really like this layout! I miss the time-feature on your scribble but I'm sure you will come up with something nice.
Question 1: Will there be the possibility to have the list of ALL your memories chronologically?
Question 2: How will you ensure that "Recents" and "Last 30 days" won't show the exact same three memories (Will they be random?)
Otherwise I like your plan!

**Comment by andy-schwedler** [comment]
> Question 1: Will there be the possibility to have the list of ALL your memories chronologically?

Yes, this will be implemented as one of the presorted sections, like "Recents"


> Question 2: How will you ensure that "Recents" and "Last 30 days" won't show the exact same three memories (Will they be random?)

Great question! Recents is not defined yet. So maybe this will change to recently created ones
