### ISSUE TITLE
redesign create form

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#35]
## Value Proposition

**As a** a beaver

**I need** an image upload and a more styled create form

**to be able to** better recall certain memories by picture 

## Description

![Image](https://user-images.githubusercontent.com/116001730/212705447-7c85d9ba-b0c3-4683-a5fa-32bdf0baf883.png)

## Acceptance Criteria

- Provides a styled textarea with styled labels
-  color contrast meets a11y criteria
- beavers can upload pictures
- buttons are styled the same
- no overlap of elements

## Tasks

- [x] work on new branch
- [x] enable bookmark button for create page
- [x] add cloudinary image upload
- [x] add count for text-input
- [x] apply styling

**Comment by ufelgen** [comment]
"fix" bookmark button? was stimmt denn nicht mit ihm? kannst du das noch ausführen?

sonst würde ich mir wünschen, dass du was spezifischeres schreibst als "looks prettier than before" - das wurde mir auch mal angekreidet und ich finde, zu Recht :) 

ich mag deine App, wollte ich mal sagen 💕
