### ISSUE TITLE
redesign detail page

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/capstone-project#36]
## Value Proposition

**As a** beaver

**I need** an option to delete and edit a memory on the dynamic page

**to be able to** correct or delete a certain memories details

## Description

![image](https://user-images.githubusercontent.com/116001730/213276974-25c3b83d-7963-4765-b5c2-38ceaa2bc40e.png)

## Acceptance Criteria

- beavers are able to edit a memory
- beavers will see a picture if uploaded

## Tasks

- [x] work on new branch
- [x] show cloudinary picture on dynamic page
- [x] display preview of picture on overview page
- [ ] implement Edit-Function to a memory
